### PR TITLE
Simplify-prepare-config

### PR DESCRIPTION
**Pull request by nbren12**
Improvements to the prepare config CLI and API. These are breaking changes

(Delete unused sections)
Added public API:
- config.duration, a more convenient way of specifying run durations.

Refactored public API:
- Removed initial condtions related arguments from `prepare-config` and the argo workflows.

### CODE REVIEW

**Comment by nbren12** [comment]
Fixed bug and running integration tests manually here: integration-test-45ca143-0d5f

**Comment by nbren12** [comment]
Fixed one more bug...new tests here: integration-test-7e4a3bd-3f8a

**Comment by oliverwm1** [comment]
I just restarted the last integration test, which looks like it got terminated for some reason.

**Comment by nbren12** [comment]
i'm confused about why the integration tests are failing. Seems unrelated.

> How would you configure the start time for a run that does not use coarsened restarts for initial conditions? I think it would be necessary to directly set the namelist.coupler_nml.current_date?

I tested this with the microphysics prognostic run script. It pulls the date from the restart files as long as  `force_date_from_namelist` is not true.

**Comment by oliverwm1** [comment]
> It pulls the date from the restart files as long as force_date_from_namelist is not true.

Sure, but what about GFS analysis initial conditions? They do not provide any date information, you need to configure it.

**Comment by nbren12** [comment]
I see. We could make an initial date timestamp an option for GFS as well.

**Pull request merged**
