### PR TITLE
Log commit SHA in wandb

### PR DESCRIPTION
**Pull request by frodre**
It's useful to know which image runs on Weights & Biases were performed on, so now if available under the environment variable `COMMIT_SHA`, the commit SHA  is logged under `wandb.config["env"]` for all scripts currently logging to wandb.

### CODE REVIEW

**Review by nbren12 — APPROVED** [review]
Great stuff! Thanks so much.

**Comment by nbren12** [comment]
@AnnaKwa Should we do the same for `fv3fit.train`?

**Comment by frodre** [comment]
> @AnnaKwa Should we do the same for `fv3fit.train`?

I added a SHA log in the `fv3fit.train` routine on this PR.  Anywhere I saw wandb logging happening will log the SHA if it's in the environment.

**Comment by nbren12** [comment]
Oh great. Thanks @frodre.

**Pull request merged**
