### PR TITLE
Decouple fv3net docker images from fv3gfs-fortran

### PR DESCRIPTION
**Pull request by nbren12**
The prognostic run dockerfile depends on ESMF and MPI from images pushed
from the fv3gfs-fortran repo. This effectively coupled the build systems
of fv3net to fv3gfs-fortran, but this repo has different concerns.
fv3net emphasize modern tools to support experimental ML, while
fv3gfs-fortran empahsize stability in bit-for-bit checksums. As a
consequence, this coupling effectively pinned this repo to ubuntu
version supported by fv3gfs-fortran (18.04), preventing fv3net from
updating to a more recent OS and software like python 3.7 (See #1083).

Building esmf, mpi, and fms in the prognostic run dockerfile effectively
decouples these repos.

The checksums remain unaltered.

### CODE REVIEW

**Comment by nbren12** [comment]
This passed tests locally. Proof:

```
$ git status                                                                                                                                                                                                                            
On branch decouple-docker-image
Your branch is up to date with 'origin/decouple-docker-image'.

nothing to commit, working tree clean
[I] noahb@noah-vm ~/w/V/fv3net (decouple-docker-image) 
$ make build_image_prognostic_run 2> /dev/null && echo "succeeded"
tools/docker_build_cached.sh us.gcr.io/vcm-ml/prognostic_run:latest \
        -f docker/prognostic_run/Dockerfile -t us.gcr.io/vcm-ml/prognostic_run:bfdff9d8fb466b50f60bcab08ea15eb6e542feaa \
        --target prognostic-run .
tools/docker_build_cached.sh us.gcr.io/vcm-ml/prognostic_run:latest \
        -f docker/prognostic_run/Dockerfile -t us.gcr.io/vcm-ml/notebook:bfdff9d8fb466b50f60bcab08ea15eb6e542feaa \
        --target notebook .
succeeded
```

**Comment by frodre** [comment]
Could we similarly push build dependency images for ESMF, MPI, FMS, NCEP to the container registry to save time rather than requiring full-rebuild after a system prune?  Or have there been issues with this in the past?

**Comment by nbren12** [comment]
@frodre Once this in master the ESMF etc steps will be cached. We already have remote caching enabled for prognostic_run image builds, but the cache is the image tagged with `:latest`. latest is still pointing to an image constructed with master, which is why this image required a long time to rebuild. When this is merged CI will push the docker image to this tag, and all the previous steps should be cached.

BTW I've tested this locally, by overwriting pushing an image to GCR and changing the CACHE_TAG here: https://github.com/VulcanClimateModeling/fv3net/blob/779ce7b70bf5e19c734defbc93667a496310eb3a/Makefile#L10

**Review by oliverwm1 — APPROVED** [review]
This looks good to me, nice to remove the coupling between fv3net and fv3gfs-fortran dockerfiles. Hopefully the caching works well once this is merged to master. Let's keep an eye on that.

**Pull request merged**
