### PR TITLE
micro: Default launches every training config

### PR DESCRIPTION
**Pull request by nbren12**
@frodre not sure if you have something like this already? Feel free to close if so.

### CODE REVIEW

**Comment by frodre** [comment]
I updated to the dense, but this will fit nicely in #1789, I think.  I'd like to get one full regression in before switching to the new dataset, so I don't think we need to close this PR.  Maybe this PR can also add in deletions of the precpd cloud water patch in.

**Comment by frodre** [comment]
Merged into the PR [Remove cron.py and add suffix to default.py](https://github.com/ai2cm/fv3net/pull/1789/commits/9a411c8b3d5fbe70d6d888bbe9e9db32762b527f)

**Comment by nbren12** [comment]
>  I'd like to get one full regression in before switching to the new dataset, so I don't think we need to close this PR.

That's a good idea. I may lower the number of epochs here to keep the number of steps similar to the v3 data. I'm getting impatient waiting for this to finish!

**Comment by nbren12** [comment]
https://wandb.ai/ai2cm/microphysics-emulation/runs/2g4snhue/overview?workspace=user-nbrenowitz

**Pull request closed without merging**
