### PR TITLE
Add RNN (x)failing downards dependence test

### PR DESCRIPTION
**Pull request by frodre**
Add a test to verify issue #1522

### CODE REVIEW

**Review by nbren12 — APPROVED** [review]
Looks awesome. For now, I think we'll want to preserve the `rnn` architecture as it currently is since it is the best configuration. Maybe we can call the fix `rnn-v1`?

**Comment by frodre** [comment]
I have it in a "fixed" branch right now as `HybridRNN` and was going to add an arch key like references that model so we can still use it.  Could also go with `RNNv1`

**Comment by frodre** [comment]
I like the `rnn-v1` and `rnn-v2` since that clearly delineates vs updated names.

**Comment by nbren12** [comment]
The advantage of using `rnn` and `rnn-v1` is that it makes it easier to know which architectures are the same in W and B.

**Comment by frodre** [comment]
Ahh, okay, so new rnn is `rnn-v1`.  That makes sense.

**Pull request merged**
